### ISSUE TITLE
Review fiscal hosting eligability requirements and terms

### ISSUE THREAD

**Issue by BenJam** [Open-Source-Collective/osc#3]
The terms of our fiscal hosting agreement need a review. And our processes for automatically accepting projects needs updating. 

I would like to keep the bar for applying to Open Source Collective as low as possible, but I would like to move to align the eligibility criteria with our values as an organisation.

- [x] [review eligibility criteria](https://app.gitbook.com/o/-LWSZizNMEjL8_DrMNdF/s/-MN_ynR0BjrarSoA9Z-A/~/diff/~/changes/Z4Mvft9N2lqLtEBlxdvK/getting-started/acceptance-criteria)
- [x] amend automatic approval processes to match the new eligibility criteria 
- [ ] review terms of fiscal sponsorship
- [ ] amend documentation and guidance to align with changes in terms

**Comment by poohlaga** [comment]
_draft in progress with @RichardLitt _

https://www.oscollective.org/#criteria

- [x] break out the need to have multiple administrators as a separate sentence 
- [x] rename this to eligibility - not criteria (sounds so dry)
- [ ] update the site page based on the internal docs edited with Richard

**Comment by RichardLitt** [comment]
Edited the basic criteria docs. Still need to work on the automatic process.

**Comment by BenJam** [comment]
just a note to say that I've linked the reviewed docs at the top which are ready to go once we have the github/manual application processes lined up.

**Comment by BenJam** [comment]
closing as a we're managing things like this in asana.
