### ISSUE TITLE
Workshops follow ups

### ISSUE THREAD

**Issue by BenJam** [Open-Source-Collective/osc#8]
- [x] gather feedback from participants
- [ ] establish metrics for projects with attendees
- [ ] reflect feedback to Sumana
- [ ] establish next phase
- [ ] ... profit.

**Comment by BenJam** [comment]
Sumana has. sent us the latest resource to add to the docs, @RichardLitt might you get a chance to have a look at that?

**Comment by BenJam** [comment]
Start gathering other candidate projects

- AzuraCast https://twitter.com/SlvrEagle23/status/1541249266861199360

**Comment by BenJam** [comment]
@BenJam to add docs and references etc.

**Comment by BenJam** [comment]
hey @RichardLitt if we could kick this off when you're back it'd be appreciated. we've been talking about this for too long!

**Comment by RichardLitt** [comment]
> gather feedback from participants

I can't find the list of participants. Do you know where it is?

**Comment by poohlaga** [comment]
Survey responses are in
Check with Jess Lord/Stormi to figure out what GitHub classes will cover, can ours augment theirs? Encourage others to go to that program but let's figure out who their ideal project is so we can fill in the gaps for who is not applicable 
Follow up w Sumana to figure out what the next workshops will be

**Comment by BenJam** [comment]
just a note to say that Richard is setting up a call with Naytri at GitHub to chat about their programme.

**Comment by RichardLitt** [comment]
And recorded a podcast this morning with them, which will go out next week.

**Comment by RichardLitt** [comment]
Also talking to Sumana on the 20th about this.
