### ISSUE TITLE
Stripe Virtual Bank Accounts

### ISSUE THREAD

**Issue by poohlaga** [Open-Source-Collective/osc#9]
A OSC collective asked if they could hook up their Patreon payments to their OSC balance as detailed in this blog post: https://blog.opencollective.com/combine-patreon-and-open-collective/

Patreon does not provide details in their pay out that would allow us to see the donations for multiple collective. Currently we transfer Homebrew's payments into their balance. Until Patreon can provide more detail in their monthly payouts, we are unable to support other collectives.

@BenJam has opened a ticket with Patreon to see if they can update their feed. 

Other examples of where this would be useful - 
https://opencollective.com/cdli/updates/classic-logo-t-shirt-available
https://opencollective.slack.com/archives/C0HSLRNVC/p1680109771457989
https://opencollective.freshdesk.com/a/tickets/184611

**Comment by BenJam** [comment]
we'll solve this with Stripe virtual bank account support

**Comment by poohlaga** [comment]
Have a call with Samantha Sconyers <ssconyers@stripe.com>, Open Collective's commercial point of contact on Friday Mar 31 to discuss pricing and next steps

**Comment by poohlaga** [comment]
Follow up from initial call with Samantha Sconyers <ssconyers@stripe.com> and Josh (contact info needed)

Two paths need exploring, technical and compliance. Unfortunately there is no way to use Stripe Treasury without integrating it into our platform and that would be the next conversation. He said ‘i’m not going to sugar coat it, it’s not an easy integration’. Right now we are on a ‘direct’ model and to use treasury we’d need to be on a ‘platform’ model which requires sub accounts.
Treasury services is ‘treasury’ and ‘issuing’ so money in and money out through virtual cards. There is no way for us to ‘test’ treasury with generating one account and a new VC.

They were also very non-aware from the compliance side how us being a fiscal sponsor may affect things. I had to explain what a fiscal sponsor is and I think they got it but I asked - what restrictions do you have because that would make it easier for us to say ‘yes’ we can adhere to that or no we cant. Am waiting for them to send us any restrictions they have. They said as an example their typical client might be a platform for barber services to let people book haircuts but each barber is an LLC and separate business entity.

Bummed because there’s not an easy ‘test’ path for the OSCA/Eventbrite idea but maybe we keep brainstorming for that.
I’m following up with our terms of sponsorship - feels like we should have a follow up conversation to understand the integration though just so we know if it is something we’d want to entertain or not - yea?

**Comment by BenJam** [comment]
fYI this is ain a bit of a state, we should hear back today from Stripe about their review which has paused our account payouts as of 15th March.

**Comment by poohlaga** [comment]
Is there another option for this?

We could just create new bank account in Umpqua for each collective and only allow deposits, no transfers out.

**Comment by BenJam** [comment]
closing as it appears that this isn't something Stripe want to offer us at this time.
